---
title: "{data.table} Translation Project - French"
format: pdf
editor: visual
---

This proposal is submitted to answer to a call for translations of the {data.table} package \[see here\](<https://rdatatable-community.github.io/The-Raft/posts/2023-10-17-translation_announcement-toby_hocking/>).

## Goal

-   Translation of all messages of the {data.table} package in French (from its `R-data.table.pot` and `data.table.pot` files, that is, 1285 messages for {data.table} version 1.15.99, commit 65212df on 2024-04-24)

-   Translation of all vignettes in French (12 `.Rmd`\` files for the same version of {data.table})

-   Translation in French of the {data.table} cheatsheet ()

## Staff

-   Lead: Philippe Grosjean \<phgrosjean\@sciviews.org\> and \<Philippe.Grosjean\@umons.ac.be\>, University of Mons, main translator in French of base and recommended R packages, using R since version 0.63, maintain many R packages in CRAN or GitHub,

-   Christian Wia \<w9204-rs\@yahoo.com\>, part of the French R translation team, retired senior engineer of Nokia International at Paris-Saclay, translator administrator EN-\>FR, on MediaWiki transverse technical projects since 2009, R contents translator since 2021.

-   Vincent Rocher \<vincent.rocher\@inrae.fr\>, post-doc MIAT unit, INRAE Toulouse. Data scientist in bioinformatics, has been using R since 2014 and data.table since 2020 to process genomic data.

-   Elise Maigné, elise.maigne\@inrae.fr, INRAE, Toulouse. Engineer in biostatistics, using R since 2009 and data.table since 2017.

-   Vincent Runge, \<vincent.runge\@univ-evry.fr\>, assistant Professor in statistics, Evry University, using R since 2012.

## Organisation

-   Work centralized in a GitHub repository (<https://github.com/phgrosjean/rfrench>).

-   Each translated sentence is revised by at least a second translator.

-   Difficult sentences may be discussed among the whole staff.

-   An English-French dictionary for several terms used in R messages is maintained for the translation of base and recommended R packages (\[here\](<https://github.com/phgrosjean/rfrench/blob/main/RFrenchDictionary.txt>)). This dictionary will be updated with terms specific to {data.table}.

## Timing

We plan to finish the translation around the beginning of September 2024. Translation of new messages for future versions of {data.table} will be done (although on an irregular basis, depending on our availability) by the French translation team of R as it is the case for base and recommended R packages since R version 2.10.0.

## Awards

Philippe: no award asked. I contribute for free to the translation of R in French. I prefer to reserve the awards for the other contributors in the team.

Christian: one award asked for my FR activity considered being at full time and for long term support. FR done with no sub dialects, on contents being messages of code (warning errors..., interface : UI, forms.. , vignettes , news, releases), working in team coordinated by Philippe , means being a centralized glossary plus common discussion forum. Informations received via alerts on GitHub or mail messages. Favorable to collaborate to the data.table translation since according to Michael Chirico statistics french reaches 267M of speakers that is the 5th position in the list and covers a wellspread community in Europe (Belgium Swiss France) Canada and Africa. Thanks.

Vincent: one award asked to compensate for the time this activity will take from my research. The translation will be carried out on messages, vignettes, and cheatsheets under the direction of Philippe Grosjean. I'm very interested to participate in the translation of data.table to help the French community use the R language and to promote its use in the data science community.

Elise: one award asked to compensate for the time this activity will take from my research.

Vincent R: one award asked to compensate for the time this activity will take from my research. I believe it is important to provide high-quality resources in languages other than English. That is why I joined the team.
